### ISSUE TITLE
Dice not working

### ISSUE THREAD

**Issue by FLF3rno** [slayer6409/Emergency-Dice-Updated#2]
Probably a v55 thing, but i really like this mod and find it pretty unfortunate.

When I throw the dice it keeps rolling slowly and does nothing

**Comment by FLF3rno** [comment]
By the way, this is not a non-host only thing

**Comment by slayer6409** [comment]
Are you on the current version? And are you able to provide me with your output log file?

**Comment by FLF3rno** [comment]
I am on the current version and i don't really know how to provide you with my output log file, when i find another die i'll try and see

**Comment by FLF3rno** [comment]
I have the log, might not be that useful but how do i send it?

**Comment by slayer6409** [comment]
You should just be able to post it here with the button that says "Paste, drop, or click to add files"

**Comment by FLF3rno** [comment]
[log.txt](https://github.com/user-attachments/files/16152248/log.txt)

I never used github before but i should have seen the attach files icon

**Comment by slayer6409** [comment]
It seems like there might be another mod causing conflicts/errors, but I am not 100% sure. I'll look into it a bit more.

**Comment by FLF3rno** [comment]
You're right and i'm sorry to have taken some of your time. The mod causing the issue is "MetalRecharging", ty for helping me

**Comment by slayer6409** [comment]
Yeah no problem! Glad you got it working!
