### ISSUE TITLE
Not getting back to regular Size after shrinking

### ISSUE THREAD

**Issue by SoliderLulinger** [slayer6409/Emergency-Dice-Updated#4]
After a "bad" roll and getting shrunk, im not getting rezied, even after death.

**Comment by slayer6409** [comment]
I'll take a look here in a sec

**Comment by slayer6409** [comment]
It should be fixed now! I just pushed the update to Thunderstore.

**Comment by ZigzagAwaka** [comment]
Hello !
Yes it's fixed ! But wanted to ask something
One member of my team got this effect and because the size was not beeing reset it made everyone laugh ! It could be nice to make it optionally infinite via a config

**Comment by slayer6409** [comment]
I can definitely do that. I can make 3 different modes for it. 
1. Return to normal upon leaving the planet
2. Return to normal upon leaving the lobby 
3. Return to normal upon getting the dice event again

**Comment by slayer6409** [comment]
The proposed changes have been done and it is uploaded to Thunderstore!

**Comment by ZigzagAwaka** [comment]
Wooo very cool bro ! Thanks
