### ISSUE TITLE
[suggestion] Compatible with LethalConfig

### ISSUE THREAD

**Issue by SoliderLulinger** [slayer6409/Emergency-Dice-Updated#5]
Hello, it would be great if this mod would be compatible with LethalConfig, so you can access the .cfg ingame.

Mod site: https://thunderstore.io/c/lethal-company/p/AinaVT/LethalConfig/

**Comment by slayer6409** [comment]
LethalConfig compatibility has been added, although it is recommended that you restart the lobby/game upon changing values.
