### ISSUE TITLE
[Incompatibility] RemoveMotionSway helmet visor

### ISSUE THREAD

**Issue by Koishukaze** [slayer6409/Emergency-Dice-Updated#6]
This mod has an incompatibility, I am able to reproduce it with just these 2 mods, here is the log
[LogOutput.log](https://github.com/user-attachments/files/17042373/LogOutput.log)

**Comment by Koishukaze** [comment]
This *does not* happen with https://thunderstore.io/c/lethal-company/p/Theronguard/Emergency_Dice/

**Comment by slayer6409** [comment]
I'll definitely take a look here in a bit

**Comment by Koishukaze** [comment]
I should mention i mean the clear hud gets reset after pulling the ship lever

**Comment by slayer6409** [comment]
Ohhh I see yeah that shouldn't be too hard to fix, I'll probably have a patch out tomorrow

**Comment by slayer6409** [comment]
I just pushed a patch to Thunderstore, if it still doesn't work, feel free to re-open the issue.

**Comment by Koishukaze** [comment]
can confirm its fixed, thank you!
